#! /usr/bin/env bash

_wal() {
	local prev_word=${COMP_WORDS[$((COMP_CWORD - 1))]}
	local cur_word=${COMP_WORDS[$COMP_CWORD]}

	if [[ "$prev_word" == "--theme" ]]; then
		local themes="$(wal --theme | awk '/-/ { print $2 }')"
		COMPREPLY=($(compgen -W "$themes" -- "$cur_word"))
	fi

	if [[ "$prev_word" == "--backend" ]]; then
		local backends="$(wal --backend | awk '/-/ { print $2 }')"
		COMPREPLY=($(compgen -W "$backends" -- "$cur_word"))
	fi
}

complete -o dirnames -F _wal wal
